import Footer from "./components/footer/footer";
import "./global_styles/reset/reset.scss";
import type { Metadata } from "next";
import LoaderComponent from "./share/loader/loader";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LoaderComponent />
        {children}
        <Footer />
      </body>
    </html>
  );
}
