import Footer from "./components/footer/footer";
import "./global_styles/reset/reset.scss";
import type { Metadata } from "next";
import LoaderComponent from "./share/loader/loader";
import { Tracker } from "./share/tracker/tracker";
import Breadcrumbs from "./share/crumbs/crumbs";
import CookieMessage from "./share/cookieMessage/cookieMessage";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <LoaderComponent />
        {children}
        <CookieMessage />
        <Footer />
        <Breadcrumbs />
        <Tracker />
      </body>
    </html>
  );
}
